name: Stylish-Boss
author: Mushroom
flag: CATF{Y0U_M4D3_1T_B0$$_Y0U_D3S3RV3_4_MU$HR00M_45_4_G1FT!}
description: |
  He’s not your ordinary boss.
He rules the floor with charm, wit, and an unmistakable sense of style.
Under the glow of the spotlight, even the shadows seem to follow his lead.

This is mushroom’s creation — the one and only Stylish Boss.
