name: Nostalgia
author: korea
flag: CATF{h3r3_1s_y0ur_fr33_k0r34n_fl4g}
description: |
  I'm really bad at game hacking and I don't have a reverse guy in my team as you know finding a reverse guy is harder than winning the lotatry. So can you help me hack this game
