name: Meow
author: K1r1too
flag: CATF{JuSt_4n_34sY_PaCk3d_CH4LLeng3}
description: |
  My cousin's cat accidentally compiled this binary while trying to sit on my keyboard. We kept it because it meows when you run it in the right mood.