name: Vibe Coded C
author: korea
flag: CATF{Th!$w4s_r3@lly_k0re@n_ch@ll3ng3}
description: I vibe coded this web server and GPT bro told me it is production ready so give up and don't try as there is no flags here
