name: Flagtionary
author: Kalawy
flag: CATF{bl4ckl1st_b3l0ngs_1n_th3_tr4sh}
description: |
  Our developer struggles with the brain fog, so he decided to create this application to help him to memorize 2 chars abbreviation.

  He forgets everything but not the flag
